version: '2'
services:
  chrome:
    image: selenium/node-chrome:4.0.0-beta-3-prerelease-20210402
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
    networks:
      vpcbr:
        ipv4_address: 10.6.0.5
  edge:
    image: selenium/node-edge:4.0.0-beta-3-prerelease-20210402
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6901:5900"
    networks:
      vpcbr:
        ipv4_address: 10.6.0.6
  firefox:
    image: selenium/node-firefox:4.0.0-beta-3-prerelease-20210402
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6902:5900"
    networks:
      vpcbr:
        ipv4_address: 10.6.0.7
  opera:
    image: selenium/node-opera:4.0.0-beta-3-prerelease-20210402
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6903:5900"
    networks:
      vpcbr:
        ipv4_address: 10.6.0.8
  selenium-hub:
    image: selenium/hub:4.0.0-beta-3-prerelease-20210402
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      vpcbr:
        ipv4_address: 10.6.0.9
  automationchrome:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - browser=chrome
    depends_on:
      - selenium-hub
    links:
      - selenium-hub
    networks:
      vpcbr:
        ipv4_address: 10.6.0.10
  automationfirefox:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - browser=firefox
    depends_on:
      - selenium-hub
    links:
      - selenium-hub
    networks:
      vpcbr:
        ipv4_address: 10.6.0.11
  automationopera:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - browser=opera
    depends_on:
      - selenium-hub
    links:
      - selenium-hub
    networks:
      vpcbr:
        ipv4_address: 10.6.0.12
  automationedge:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - browser=edge
    depends_on:
      - selenium-hub
    links:
      - selenium-hub
    networks:
      vpcbr:
        ipv4_address: 10.6.0.13
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1
